version: "3.8"

networks:
  domain-checker-nw:

services:
  nginx:
    image: nginx:1.19.5-alpine
    container_name: domain-checker-nginx
    working_dir: /app
    volumes: 
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - domain-checker-nw

  php-fpm:
    build: docker/php-fpm
    container_name: domain-checker-php-fpm
    working_dir: /app
    volumes: 
      - .:/app
      - ./docker/php-fpm/php-ini-override.ini:/etc/php7.4/fpm/conf.d/99-overrides.ini
    environment: 
      XDEBUG_CONFIG: "remote_host:127.0.0.1"
    networks:
      - domain-checker-nw